<a href="https://colab.research.google.com/github/rhqtmfajfl/python-study/blob/master/rhqtmfajfl/python-study/colab/03_%EB%8B%A4%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4%EC%9D%98_%EC%97%B0%EC%82%B00621.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 배열의 정보 확인

In [ ]:
A = np.array([1,2,3,4])

print(A.ndim)
print(A.shape) #하나씩만 있어야 하는 데이터 편향과 출력 밖에 없다.




1
(4,)


In [ ]:
B = np.array([[1,2],
              [3,4],
              [5,6]])

print(B.ndim) #2차원이 나온다.
print(B.shape)

2
(3, 2)


# 행렬의 내적

2차원 배열인 행렬의 내적을 구하는 방법

$$
\begin{pmatrix}
a & b \\
c & d \\
\end{pmatrix}
\times
\begin{pmatrix} 
p & q \\
r & s \\
\end{pmatrix}
= \begin{pmatrix} 
ap+br & aq+bs \\
cp+dr & cq+ds \\
\end{pmatrix}
$$

행렬의 내적은 
* 왼쪽 행렬의 행(가로)과 오른쪽 행렬의열(세로)을 원소 별로 곱하고 그 값들을 더한다.

* 계산의 결과가 새로운 다차원 배열의 원소가 된다.
*행렬은 보통 대문자로 표기하는 것이 관례

In [ ]:
A =np.array([[1,2],
             [3,4]])

B = np.array([[5,6],
              [7,8]])

print('A.shape : {}'.format(A.shape)) # 행과 열을 나타냄
print('B.shape : {}'.format(B.shape))

A.shape : (2, 2)
B.shape : (2, 2)


In [ ]:
## A와 B의 행렬의 열과 행부분이 같으면 내적이 된다. 



In [ ]:
print(np.dot(A,B))
print()
print(A @ B)

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


### 행렬 내적의 특징

* 교환 법칙이 성립되지 않는다.

$$
A \cdot B \ne B \cdot A
$$

In [ ]:
B @ A

# 행과 열의 개수가 다른 상태에서의 행렬 내적
첫 번째 행렬의 첫 번째 차원의 원소 수(열의 수) 와 두  번째 행렬의 0번째 차원의 원소수(행의 수)가 일치해야 한다.

In [ ]:
A = np.arange(1, 7).reshape(2,3)
B = np.arange(1,7).reshape(3,2)

print(A.shape)
print(B.shape)

(2, 3)
(3, 2)


In [ ]:
A @ B

array([[22, 28],
       [49, 64]])

In [ ]:
B @ A

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

# 차원수가 달라도 계산은 가능하다.

하지만 계산하려는 행렬들에서 첫번째 행렬의 열과 두번째 행렬의 행의 수가 같아야 한다.

In [ ]:
A = A.reshape(3,2)
B = np.array([7,8]) # 

#(7
# 8) 이런 형식으로 된다.

print(A.shape)
print(B.shape)

# @ 와 dot 은 같은 의미 이다.


(3, 2)
(2,)
