<a href="https://colab.research.google.com/github/rhqtmfajfl/python-study/blob/master/rhqtmfajfl/python-study/colab/ai_class_0601_numpy%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

numpy 수치연산을 위한 파이썬 라이브러리

In [ ]:
#1. python의 list를 ndarray화 할 수 있따.
py_list = [1,2,3]
arr1 = np.array(py_list)
arr1

array([1, 2, 3])

In [ ]:
#타입확인
type(arr1)


numpy.ndarray

In [ ]:
np.ones((2,3))*5 #5로 채워진 배열

array([[5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
np.full((2,3),5) #np.full 사용빈도 낮은 zeros가 많이 사용 zeros 딥러닝 머신러닝에서 편향 초기값

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
#점구간 만들기
np.linspace

<function numpy.linspace>

In [ ]:
np.linspace(1, 10, 3) #1부터 10까지 3개의 숫자를 균일한 구간으로 만든다. -> 균일한 두개의 구간을 생성

array([ 1. ,  5.5, 10. ])

In [ ]:
#linspace 시각화 선을 그을 용도록 사용 구간값

In [ ]:
np.linspace(1, 10,4)

array([ 1.,  4.,  7., 10.])

In [ ]:
#arndom

In [ ]:
#완전랜덤 rand

np.random.rand(2,3)

array([[0.77115231, 0.84272711, 0.01145006],
       [0.56105879, 0.57537581, 0.44440887]])

In [ ]:
np.random.rand(2,3,4)

array([[[0.19138774, 0.76268514, 0.362055  , 0.86297825],
        [0.06305797, 0.91340392, 0.9937279 , 0.7587652 ],
        [0.60416864, 0.89512776, 0.13717826, 0.47153364]],

       [[0.99666777, 0.76912059, 0.35137122, 0.41745383],
        [0.62487498, 0.25836737, 0.94402707, 0.04391182],
        [0.35481777, 0.9899136 , 0.01569559, 0.97552521]]])

In [ ]:
#정규분포 랜덤 값의 빈도가 평균이 많고 최소최대로 갈수록 값이 작아진다.

In [ ]:
np.random.randn(16)

array([-1.31444232, -0.32462234, -0.38652715, -0.90281185,  0.95989146,
        1.47910273, -0.90527509, -0.35506866, -1.17491388,  1.16267495,
       -0.00970957,  0.85806699, -1.65927629,  0.32726356,  1.82769645,
        0.35650065])

In [ ]:
#균등분포

In [ ]:
np.random.uniform(1.0, 3.0, size=(3,4)) #균등분포는 구간이 필요하다

array([[1.79865977, 2.14779534, 2.20160197, 2.06051842],
       [1.42294994, 1.84120156, 2.22034323, 1.74753318],
       [1.57495941, 1.42606593, 1.12940173, 1.01521466]])

In [ ]:
## 정수랜덤 샘플링

In [ ]:
np.random.choice(10, size=(2,3)) #0부터 9까지 정수중 랜덤하게 2,3배열 형태로 추출 기본은 중복 추출


array([[2, 3, 3],
       [7, 1, 9]])

In [ ]:
#배열내에서도 랜덤 추출이 가능

In [ ]:
arr = np.arange(1,6)
np.random.choice(arr, size=(2,2))

array([[4, 5],
       [2, 1]])

In [ ]:
arr = np.arange(1,6)
np.random.choice(arr, size=(2,3))

array([[3, 2, 5],
       [2, 1, 4]])

In [ ]:
#중복추출 x

In [ ]:
np.random.choice(arr, size=(2,2), replace= False) #중복추출 x - replace 옵션을 alse로 주면 추출x

array([[2, 3],
       [5, 1]])

In [ ]:
#랜덤 정수 배열 만들기
a1 = np.random.randint(1, 100, size=(5,))

In [ ]:
a1

array([89, 62, 13, 73, 12])

In [ ]:
a2 = np.random.randint(1, 100, size=(5,1))

In [ ]:
a2

array([[50],
       [22],
       [ 2],
       [69],
       [54]])

In [ ]:
#다차원배열 노션 2-1 행렬

In [ ]:
#스칼라 0차원 데이터

#벡터 실수값 x가 모여져 있는것 -> 스칼라를 모은것 1차원 배열
#a =[1,2,3] 모아진 n개의 개수가 n차원이 된다. n차원 벡터
#열벡터를 기본으로 한다.

In [ ]:
#행벡터의 모양을 하지만 1차원 배열이기 때문에 열벡터로 따져야 한다.
heights_1 = np.array([180.1,175.5,163.3])
heights_1

array([180.1, 175.5, 163.3])

In [ ]:
h_2 =np.array([[180.1],
               [175.5],
               [163.3]])
h_2  #이차원배열 이것도 벡터가 된다. 열벡터가 된다.

array([[180.1],
       [175.5],
       [163.3]])

In [ ]:
#열벡터를 띄거나 2차원 배열일 때사이킷런 텐서플로우 같은 머신러닝에서 사용

#이차원 배열이지만 열백터의 모양을 하고 있으면 허용 행백터 모형은 에러

In [ ]:
#heights_1과 h2는 다른 배열이다. 하지만 같은 백터이다.
#h1은 numpy에서는 행벅터이지만 실제 수학적으로 열벡터이다.
#hws
#벡터 x = [3,5] 이면 3,5로 가는 것

In [ ]:
#행렬 matrix = 2차원 배열
#1차원 배열인 백터가 여러개 모여 있는것

In [ ]:
#ensor 텐서
#3차원 이상의 매열을 의미
#3차원 배열은 2차원 베에 모영;ㅅ다.

In [ ]:
#0 fank tensor - 스칼라이다. 0차원

In [ ]:
#axis 이해하기


axis 이해하기
axis : 축. 축이란? 데이터가 추가되는 방향의 인덱스

예를 들어서 3차원 (3, 4, 5)

3차원 배열에 추가되는건 2차원 배열 -> axis=0
2차원 배열에 추가되는건 1차원 배열 -> axis=1
1차원 배열에 추가되는건 0차원 스칼라 -> axis=2

axis 가 1이라는 것은 1차원 배열에 추가되는 2차원의 방향

In [ ]:
arr = np.arange(1, 37).reshape(3,4,3)

In [ ]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [ ]:
arr = np.arange(1, 37).reshape(3,4,3)

In [ ]:
np.max(arr,axis=0) #axis

array([[25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [ ]:
np.max(arr, axis=1)

array([[10, 11, 12],
       [22, 23, 24],
       [34, 35, 36]])

In [ ]:
np.max(arr, axis=2)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [ ]:
arr = np.random.randint(1, 37, size=(3,3,3,3))
arr

array([[[[ 1, 29, 26],
         [ 1, 35, 18],
         [33, 19, 24]],

        [[19, 30, 31],
         [ 2, 33, 34],
         [ 4, 27, 19]],

        [[27, 35, 31],
         [27, 31,  9],
         [24, 17,  1]]],


       [[[19, 22, 36],
         [20, 30,  6],
         [12, 23,  8]],

        [[32, 15, 32],
         [23,  5,  5],
         [13, 13, 29]],

        [[21, 32, 30],
         [11,  3, 19],
         [17,  4,  2]]],


       [[[16, 27, 23],
         [31, 17, 32],
         [ 3, 16, 34]],

        [[16, 12, 11],
         [ 4, 19, 28],
         [33,  4, 30]],

        [[21, 21,  2],
         [12, 24,  6],
         [19,  5,  1]]]])

In [ ]:
arr = np.random.randint(1, 37, size=(3,4,3))
arr

array([[[22, 13, 28],
        [ 5,  8, 29],
        [32, 28,  6],
        [32,  3, 12]],

       [[36, 18,  1],
        [13,  6,  5],
        [ 4, 11, 24],
        [17, 12, 27]],

       [[ 5, 24,  2],
        [20, 26, 24],
        [ 1, 13, 28],
        [19, 28, 11]]])

In [ ]:
arr1 = arr[0:3,1:3,1:3] #첫번째 전체 행렬 두번째는
arr1

array([[[ 8, 29],
        [28,  6]],

       [[ 6,  5],
        [11, 24]],

       [[26, 24],
        [13, 28]]])

In [ ]:
#spread 연산자

In [ ]:
arr = np.arange(36).reshape(2,3,3,2)
arr

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]]])

In [ ]:
arr [0, : ,: ,0]  #첫번째가 가장높은 차원 두번째가 그다음 차원

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
#spread 연산자 사이 값을 다 뽑고 싶을 때 사용

In [ ]:
arr [0,... ,0]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
#차원 추가(차원수 확장)


보통 이미지 데이터를 딥러닝에서 사용하고자 하면 : (N, H, W, C)

N : 이미지의 개수
H : 세로 픽셀의 개수
W : 가로 픽셀의 개수
C : 채널수(컬러 RGB : 3, GRAYSCALE : 1

In [ ]:
# 훈련에 사용할 이미지의 형상(shape)을 확인 : (60000, 28, 28, 1)
# matplotlib에서 흑백 이미지를 표시하고 싶으면 (28, 28)
# images = [60000, 28, 28, 1] -> images[0, ..., 0] -> (28, 28)

# 차원 추가( 차원수 확장 )

> 들여쓴 블록


* 흑백 이미지를 가져 왔는데 형상이 `(28, 28)`
* 딥러닝에서 이미지를 다루고자 하면 `(N,H,W,C)`를 유지 해야 한다.
* `(28, 28)` -> `(1, 28, 28, 1)`로 만들어야 딥러닝에서 다룰 수가 있다.
* 원하는 차원 위치에 `np.newaxis`를 추가하면 된다.
  * numpy : `np.newaxis`
  * tensorflow : `tf.newaxis`

In [ ]:
arr = np.random.rand(28, 28)
arr.shape

(28, 28)

In [ ]:
temp_arr = arr[np.newaxis, ..., np.newaxis]
temp_arr.shape

(1, 28, 28, 1)

In [ ]:
temp= arr[np.newaxis, :,:,np.newaxis]
temp.shape

(1, 28, 28, 1)

In [ ]:
#차원 쥐어 짜기
#np.squeeze 개수가 1인 차원의 내용을 없애는 기법

In [ ]:
temp.shape

(1, 28, 28, 1)

In [ ]:
temp_squeeze = np.squeeze(temp)
temp_squeeze.shape

(28, 28)

In [ ]:
#평탄화
#2차원 배열을 1차원 배열로 평평하게 해주는것 중요!!!! 무조건 1차원으로만

평탄화
2차원 이상의 배열을 1차원 배열로 평평하게 펴주는 것 (★★★★★)
ravel : 원본 배열을 평탄화 시킨 참조배열을 만들어 낸다. (View 또는 Reference라고 한다.)
flatten : 원본 배열을 평탄화 시킨 복사된배열을 만들어 낸다.
ravel은 원본 배열에 수정이 가해질 가능성이 있고, flatten은 원본 배열에 영향을 미치지 않는다.

In [ ]:
x = np.random.randint(15, size=(3,5))
x.shape

(3, 5)

In [ ]:
x


array([[ 8,  5,  5, 10,  5],
       [14,  0, 10,  7, 13],
       [ 2,  5,  1, 13, 11]])

In [ ]:
#ravel

In [ ]:
temp = np.ravel(x) # 위의 x를 1차원으로 평탄화 1차원으로 만듬


In [ ]:
temp.shape

(15,)

In [ ]:
temp

array([ 8,  5,  5, 10,  5, 14,  0, 10,  7, 13,  2,  5,  1, 13, 11])

In [ ]:
temp[0] =100

In [ ]:
temp

array([100,   5,   5,  10,   5,  14,   0,  10,   7,  13,   2,   5,   1,
        13,  11])

In [ ]:
x #x도 같이 바뀜

array([[100,   5,   5,  10,   5],
       [ 14,   0,  10,   7,  13],
       [  2,   5,   1,  13,  11]])

In [ ]:
x[1][3] =5000 #ravel 로 만든 temp는 원본이 바뀌면 temp도 바뀐다 주소가 서로 같기 때문에
temp

array([ 100,    5,    5,   10,    5,   14,    0,   10, 5000,   13,    2,
          5,    1,   13,   11])

In [ ]:
#flatten

In [ ]:
temp_flat = x.flatten()

In [ ]:
temp_flat

array([ 100,    5,    5,   10,    5,   14,    0,   10, 5000,   13,    2,
          5,    1,   13,   11])

In [ ]:
temp_flat[0] = 1234234
temp_flat

array([1234234,       5,       5,      10,       5,      14,       0,
            10,    5000,      13,       2,       5,       1,      13,
            11])

In [ ]:
x

array([[ 100,    5,    5,   10,    5],
       [  14,    0,   10, 5000,   13],
       [   2,    5,    1,   13,   11]])

In [ ]:
#flatten은 원본데이터를 안전하게 관리할 수 있다.

In [ ]:
# 스택에는 로컬 변수만 들어간다.
#heap에는 객체만 들어간다.
#static에는 함수가 들어간다. static은 메소드 클래스라고 한다.

In [ ]:
#reshape

In [ ]:
a = np.random.randint(40, size=(2,3,3))

In [ ]:
a

array([[[23, 11, 39],
        [22, 27, 39],
        [21, 18, 37]],

       [[39, 17, 27],
        [15, 10, 39],
        [11, 17, 31]]])

In [ ]:
np.max(a, axis=1)

array([[23, 27, 39],
       [39, 17, 39]])

In [ ]:
x = np.arange(20)

In [ ]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
#reshape 팁 : reshape 함수 내의 모든 숫자들 곱했을 때 스칼라 원소의 개수와 같으면 된다.

In [ ]:
x.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
#reshape의 -1은 조커

In [ ]:
x.reshape(2, -1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
#x.reshape(2, -1,-1) #이거는 에러가 발생

In [ ]:
# arr = np.random.randn((60000,28,28,1))
# arr.shape

TypeError: ignored

In [ ]:
# arr.reshape(600, -1)

ValueError: ignored

In [ ]:
#브로드 캐스팅

#차원수가 다른 배열끼리 연산
#차원이 달라도 0차원 스칼라의 개수가 똑같으면 연산이 가능
#저차원 배열을 고차원 배열로 확장
#수학적으로 따지게 되면 고차원 배열의 shape과 똑같이 생긴 1벡터를 만들어서 저차원 배열과 곱한 배열을 만들어서 계산
#저차원을 고차원으로 임시로 늘여준다.

In [ ]:
#shape 이 다를 때의 연산

# shape이 다를 때의 연산

In [ ]:
a = np.arange(12).reshape(4, 3)  # (4, 3)
b = np.arange(100, 103)          # ()
c = np.arange(1000, 1004) 
d = np.arange(100, 103) 
e = np.arange(100, 103) 

In [ ]:
#전치행렬
#행렬 a의 행과 열의 인덱스를 바꾼것을 전치행렬
#aij를 aji로 바꾼것
#인덱스가 한개일때 는 전치가 안된다.
#인덱스가 한개 1차원 배열 일때는 reshpapeㄱ