<a href="https://colab.research.google.com/github/rhqtmfajfl/python-study/blob/master/rhqtmfajfl/python-study/colab/python_study_%EB%B3%B5%EC%8A%B5_0601_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#파이썬 numpy의 배열 ndarry

In [ ]:
#python의 list를 ndarry화 할 수 있따.
pylist = [1,2,3]
arr1 = np.array(pylist)
arr1

array([1, 2, 3])

In [ ]:
#점구간 만들기
#np.linspace
#시각화에서 선을 그을 용도로 보통 사용

np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

### Random을 사용하기 위한 Numpy
랜덤 배열은 딥러닝에서 매개변수(가중치 W,편향 b)를 초기화 하기 위해서 사용
초기화 : 최초에 가지고 있는 값을 만드는 과정
번외

생성자? : 객체 초기화 메소드
클래스를 이용해서 객체를 만들 때 객체가 처음 가지고 있어야 하는 값을 세팅하는 메소드

### 완전 랜덤 만들기
np.random.rand : 정규 분포나 균등분포가 아닌 완벽한 랜덤

In [ ]:
np.random.rand(2,3) #2,3행의 행렬에 랜덤으로 값이 들어간다.

array([[0.29858139, 0.30294405, 0.06990616],
       [0.66953957, 0.452536  , 0.69306974]])

In [ ]:
np.random.rand(2,3,4) #3차원에 2개의 2차원 행렬들어가고 1차원 행렬 3개와 스칼라가 4개 들어가는 3차원 해열ㄹ이 생긴다.

array([[[0.6904361 , 0.27029349, 0.6824115 , 0.48766678],
        [0.37073304, 0.20500686, 0.63480447, 0.45376521],
        [0.63986732, 0.40321586, 0.03968781, 0.10893507]],

       [[0.66011599, 0.58889697, 0.11010343, 0.95209146],
        [0.72634875, 0.31846587, 0.78240557, 0.16642937],
        [0.81284589, 0.96235232, 0.81221543, 0.20513182]]])

### *이탤릭체 텍스트*## 정규분포 랜덤
# * `np.random.randn`

In [ ]:
np.random.randn(16)

array([-2.30943095, -0.09930834, -1.0456947 ,  1.40063039, -0.5011222 ,
       -0.96708189,  0.30731288,  2.2426233 ,  1.59872782, -1.69324717,
       -0.49969723, -0.98712499, -1.15690271,  0.87983278, -0.53564083,
        0.02475454])

In [ ]:
np.random.randint(6)

3

### 균등분포 랜덤
np.random.uniform

In [ ]:
np.random.uniform(1.0, 3.0, size = (3,4))

array([[1.13394012, 2.70539217, 1.81896164, 1.27634443],
       [1.80247582, 1.57356908, 2.80826297, 2.57706636],
       [2.10917642, 2.71045513, 2.8558329 , 2.31348323]])



```
# 코드로 형식 지정됨
```

## 정수 랜덤 샘플링
* `np.random.choice`
* 샘플링 : 전체에서 일부를 추출하는 행위
* 딥러닝에서는 `mini-batch`를 만들 때 사용

numpy.random.uniform(low, high, size)를 이용하여 low~high 사이의 균일한 분포의 무작위 배열을 반환합니다.

numpy.random.lognormal(mean, sigma, size)를 이용하여 평균과 시그마를 대입한 로그 정규 분포의 무작위 배열을 반환합니다.

numpy.random.laplace(loc, scale, size) : μ와 λ를 대입한 라플라스 분포의 무작위 배열을 반환합니다.



In [ ]:
np.random.uniform(1.0, 3.0, size=(3,4)) #1에서 3사이의 균일한 분포의 무작위 수 반환하는데 3,4행을 나타낸다.

array([[1.47902437, 2.11399293, 1.32040006, 1.60071194],
       [2.23171842, 2.94171032, 1.30679704, 1.49511065],
       [2.79960334, 2.3019891 , 1.74507199, 1.38605048]])

In [ ]:
np.random.lognormal(3, 1, size =(2, 2))

array([[26.58865015, 19.63890317],
       [21.19385779, 16.8439695 ]])

### 텐서 - tensor
  3차원 이상의 배열을 의미한다.

  3차원 배열(3차원 텐서)은 2차원 배열이 모여있다.

  4차원 배열(4차원 텐서)은 3차원 배열이 모여있다.

  N차원 배열을 그냥 텐서라고 한다.

N이 꼭 3부터는 아니에요...

    텐서의 개념을 활용하면 모든 배열의 모양을 이야기 할 수 있다.

    0 Rank Tensor - 스칼라
    1 Rank Tensor - 벡터
    2 Rank Tensor - 행렬
    3 Rank Tensor - 3랭크 텐서...
    Tensorflow는 뭘까요...?

    구글에서 제공하는 딥러닝 프레임워크
  Tensor를 흘린다(flow)
  미리 흘릴 네트워크를 준비하고 거기에 배열(데이터)을 흘린다.

### axis 이해하기

In [ ]:
arr = np.random.randint(1, 37, size=(3,3,3,3))
arr

array([[[[10, 33, 27],
         [36,  2, 30],
         [13, 16, 15]],

        [[ 4,  7, 18],
         [34,  2, 36],
         [30, 21, 20]],

        [[16,  9, 32],
         [33, 30, 14],
         [ 6, 20, 25]]],


       [[[23,  4,  2],
         [ 6, 13, 32],
         [ 2, 27,  7]],

        [[28,  3, 12],
         [29, 15, 28],
         [33,  8, 16]],

        [[35, 13, 33],
         [17, 15, 10],
         [19,  8, 34]]],


       [[[ 7, 34, 25],
         [35,  3, 18],
         [23,  8, 22]],

        [[12,  7, 21],
         [10, 33, 19],
         [10, 25,  6]],

        [[35, 25, 25],
         [34,  3, 16],
         [ 3,  6, 26]]]])

In [ ]:
a = np.random.randint(6, size=(2, 3)) # 2차원 배열
a

array([[5, 4, 2],
       [4, 3, 5]])

In [ ]:
a = np.arange(36).reshape(3,4,3)

In [ ]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

### 슬라이싱

In [ ]:
arr = np.arange(1,37).reshape(3,4,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [ ]:
arr[ : , 2:3, 1:]

array([[[ 8,  9]],

       [[20, 21]],

       [[32, 33]]])

### 차원 추가( 차원수 확장 )
  흑백 이미지를 가져 왔는데 형상이 (28, 28)
  딥러닝에서 이미지를 다루고자 하면 (N,H,W,C)를 유지 해야 한다.

  (28, 28) -> (1, 28, 28, 1)로 만들어야 딥러닝에서 다룰 수가 있다.

  원하는 차원 위치에 np.newaxis를 추가하면 된다.
  
      numpy : np.newaxis
      tensorflow : tf.newaxis

### 차원 쥐어짜기

In [ ]:
#np.squeeze
#개수가 1인 차원의 내용을 없애는 기법

In [ ]:
arr = np.random.rand(28, 28)
arr.shape

(28, 28)

In [ ]:
tmp = arr[np.newaxis, :, :, np.newaxis]
tmp

array([[[[0.66237874],
         [0.24980343],
         [0.60754983],
         [0.37617954],
         [0.55430631],
         [0.72440199],
         [0.58143266],
         [0.08557926],
         [0.62850487],
         [0.47281558],
         [0.36212576],
         [0.34417618],
         [0.83266439],
         [0.6389115 ],
         [0.48323605],
         [0.02977193],
         [0.11582509],
         [0.289729  ],
         [0.53537826],
         [0.31409768],
         [0.40913357],
         [0.5900114 ],
         [0.77273897],
         [0.42160124],
         [0.73936009],
         [0.2069451 ],
         [0.24632907],
         [0.38215437]],

        [[0.18258336],
         [0.34760895],
         [0.03287685],
         [0.92774985],
         [0.37523631],
         [0.38870948],
         [0.74816317],
         [0.36841659],
         [0.99247437],
         [0.3641989 ],
         [0.87203203],
         [0.46340515],
         [0.87721766],
         [0.26886672],
         [0.42405391],
         