In [33]:
import numpy as np
import pandas as pd

In [ ]:
t = [i*3 for i in range(1,11)]

In [ ]:
a = [1,2,3]
b = [4,5,6]
c = [a,b]

In [ ]:
np1 = np.array(t)

In [ ]:
type(np1)

numpy.ndarray

In [ ]:
np1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
tt1 = [i for i in range(1, 10, 2)]
tt2 = [i*3 for i in range(5, 10,3)]
tt3 = [i for i in range(1, 20, 5)]

In [ ]:
ttt = [tt1, tt2, tt3]

In [ ]:
np22 = np.array(ttt)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [ ]:
type(ttt)

list

In [ ]:
np22

array([list([1, 3, 5, 7, 9]), list([15, 24]), list([1, 6, 11, 16])],
      dtype=object)

In [ ]:
type(np22)

numpy.ndarray

In [ ]:
np1 = np.array(t)

In [ ]:
np1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
np1 +1

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [ ]:
np1.shape

(10,)

In [ ]:
np1.mean()

16.5

In [ ]:
ytes

NameError: ignored

In [ ]:
np1.nbytes

80

In [ ]:
a

[1, 2, 3]

In [ ]:
b

[4, 5, 6]

In [ ]:
c

[[1, 2, 3], [4, 5, 6]]

In [ ]:
np2 = np.array(c)

In [ ]:
np2.shape

(2, 3)

In [ ]:
np2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np2.nbytes

48

In [ ]:
np2 + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
np2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
tt1 = [i for i in range(2,21, 2)]

In [ ]:
tt2 = [i*3 for i in range(1, 11)]

In [ ]:
tt3 = [i for i in range(5,51,5)]

In [ ]:
tt1, tt2, tt3

([2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
 [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
 [5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
ttt= [tt1,tt2,tt3]

In [ ]:
np22 = np.array(ttt)

In [ ]:
np22

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]])

In [ ]:
tt1 = [i for i in range(1, 10)]

In [ ]:
tt2 = [i for i in range(2, 11)]

In [ ]:
tt3 = [i for i in range(5, 12,3)]

In [ ]:
ttt = [tt1, tt2, tt3]

In [ ]:
np22 = np.array(ttt)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [ ]:
np22.sum(axis=1)

array([110, 165, 275])

In [ ]:
a = []

SyntaxError: ignored

In [ ]:
a

0

In [ ]:
b

0

In [ ]:
np11 = np.array([2,4,6,8,10])  

In [ ]:
np11.nbytes

40

In [ ]:
np11.dtype

dtype('int64')

In [ ]:
np12 = np.array([2,4,6,8,10], dtype =np.int16)

In [ ]:
np200 = np.array([2.3, 4.5, 6.7])

In [ ]:
for i in range(1, 10):

SyntaxError: ignored

In [ ]:
for i in range(1, 10):
  print('%d 단' % i)
  for j in range(2,10):
    a = i*j
    print('%d x %d = %d'%(j,i, a))

1 단
2 x 1 = 2
3 x 1 = 3
4 x 1 = 4
5 x 1 = 5
6 x 1 = 6
7 x 1 = 7
8 x 1 = 8
9 x 1 = 9
2 단
2 x 2 = 4
3 x 2 = 6
4 x 2 = 8
5 x 2 = 10
6 x 2 = 12
7 x 2 = 14
8 x 2 = 16
9 x 2 = 18
3 단
2 x 3 = 6
3 x 3 = 9
4 x 3 = 12
5 x 3 = 15
6 x 3 = 18
7 x 3 = 21
8 x 3 = 24
9 x 3 = 27
4 단
2 x 4 = 8
3 x 4 = 12
4 x 4 = 16
5 x 4 = 20
6 x 4 = 24
7 x 4 = 28
8 x 4 = 32
9 x 4 = 36
5 단
2 x 5 = 10
3 x 5 = 15
4 x 5 = 20
5 x 5 = 25
6 x 5 = 30
7 x 5 = 35
8 x 5 = 40
9 x 5 = 45
6 단
2 x 6 = 12
3 x 6 = 18
4 x 6 = 24
5 x 6 = 30
6 x 6 = 36
7 x 6 = 42
8 x 6 = 48
9 x 6 = 54
7 단
2 x 7 = 14
3 x 7 = 21
4 x 7 = 28
5 x 7 = 35
6 x 7 = 42
7 x 7 = 49
8 x 7 = 56
9 x 7 = 63
8 단
2 x 8 = 16
3 x 8 = 24
4 x 8 = 32
5 x 8 = 40
6 x 8 = 48
7 x 8 = 56
8 x 8 = 64
9 x 8 = 72
9 단
2 x 9 = 18
3 x 9 = 27
4 x 9 = 36
5 x 9 = 45
6 x 9 = 54
7 x 9 = 63
8 x 9 = 72
9 x 9 = 81


In [ ]:
array = [[i*j for j in range(2,10)] for i in range(1,10)]
print(array)

[[2, 3, 4, 5, 6, 7, 8, 9], [4, 6, 8, 10, 12, 14, 16, 18], [6, 9, 12, 15, 18, 21, 24, 27], [8, 12, 16, 20, 24, 28, 32, 36], [10, 15, 20, 25, 30, 35, 40, 45], [12, 18, 24, 30, 36, 42, 48, 54], [14, 21, 28, 35, 42, 49, 56, 63], [16, 24, 32, 40, 48, 56, 64, 72], [18, 27, 36, 45, 54, 63, 72, 81]]


In [ ]:
array = list([i*j for j in range(2,10)] for i in range(1,10))
print(array)

[[2, 3, 4, 5, 6, 7, 8, 9], [4, 6, 8, 10, 12, 14, 16, 18], [6, 9, 12, 15, 18, 21, 24, 27], [8, 12, 16, 20, 24, 28, 32, 36], [10, 15, 20, 25, 30, 35, 40, 45], [12, 18, 24, 30, 36, 42, 48, 54], [14, 21, 28, 35, 42, 49, 56, 63], [16, 24, 32, 40, 48, 56, 64, 72], [18, 27, 36, 45, 54, 63, 72, 81]]


In [ ]:
a = list(i for i in range(1,10))
    print('%d 단' % i)
    a= [i]
        for j in range(2,10):
          c= list('[j]*[i] =

IndentationError: ignored

In [ ]:
np12 = np.array(array, dtype =np.int16)

In [ ]:
np12.nbytes

144

In [ ]:
array[4] + 50
print(array)

TypeError: ignored

In [ ]:
for i in range(1,10):
  print('%d' % i)
  for j in range(2,10):
    
    print( )  

1


TypeError: ignored

In [ ]:
a = list([i*j for j in range(2,10)] for i in range(1,10))
print(a)

[[2, 3, 4, 5, 6, 7, 8, 9], [4, 6, 8, 10, 12, 14, 16, 18], [6, 9, 12, 15, 18, 21, 24, 27], [8, 12, 16, 20, 24, 28, 32, 36], [10, 15, 20, 25, 30, 35, 40, 45], [12, 18, 24, 30, 36, 42, 48, 54], [14, 21, 28, 35, 42, 49, 56, 63], [16, 24, 32, 40, 48, 56, 64, 72], [18, 27, 36, 45, 54, 63, 72, 81]]


In [ ]:
array[2:3]

[[6, 9, 12, 15, 18, 21, 24, 27]]

In [ ]:
array[2:3] +50

TypeError: ignored

In [ ]:
array[2:5,2:4]

TypeError: ignored

In [ ]:
a = np.array.reshape(8,9)

AttributeError: ignored

In [ ]:
np.array

<function numpy.array>

In [ ]:
a = np.array

In [ ]:
array

[[2, 3, 4, 5, 6, 7, 8, 9],
 [4, 6, 8, 10, 12, 14, 16, 18],
 [6, 9, 12, 15, 18, 21, 24, 27],
 [8, 12, 16, 20, 24, 28, 32, 36],
 [10, 15, 20, 25, 30, 35, 40, 45],
 [12, 18, 24, 30, 36, 42, 48, 54],
 [14, 21, 28, 35, 42, 49, 56, 63],
 [16, 24, 32, 40, 48, 56, 64, 72],
 [18, 27, 36, 45, 54, 63, 72, 81]]

In [ ]:
a = np.array

SyntaxError: ignored

In [ ]:
a

<function numpy.array>

In [ ]:
print(a)

<built-in function array>


In [ ]:
a = list([i*j for j in range(2,10)] for i in range(1,10))
print(a)

[[2, 3, 4, 5, 6, 7, 8, 9], [4, 6, 8, 10, 12, 14, 16, 18], [6, 9, 12, 15, 18, 21, 24, 27], [8, 12, 16, 20, 24, 28, 32, 36], [10, 15, 20, 25, 30, 35, 40, 45], [12, 18, 24, 30, 36, 42, 48, 54], [14, 21, 28, 35, 42, 49, 56, 63], [16, 24, 32, 40, 48, 56, 64, 72], [18, 27, 36, 45, 54, 63, 72, 81]]


In [ ]:
b = np.a()

AttributeError: ignored

In [ ]:
b = a.reshape(9,8)

AttributeError: ignored

In [29]:
a = list([i*j for j in range(2,10)] for i in range(1,10))
print(a)

[[2, 3, 4, 5, 6, 7, 8, 9], [4, 6, 8, 10, 12, 14, 16, 18], [6, 9, 12, 15, 18, 21, 24, 27], [8, 12, 16, 20, 24, 28, 32, 36], [10, 15, 20, 25, 30, 35, 40, 45], [12, 18, 24, 30, 36, 42, 48, 54], [14, 21, 28, 35, 42, 49, 56, 63], [16, 24, 32, 40, 48, 56, 64, 72], [18, 27, 36, 45, 54, 63, 72, 81]]


In [32]:
b = np.a

NameError: ignored

In [31]:
a[ :7 , 3: ] 

TypeError: ignored

In [38]:
np11 = np.array([2,4,6,8], dtype=np.int16)
np12 = np.array([3,6,9,12,15], dtype=np.int16)

In [39]:
np11.shape

(4,)

In [41]:
np11 +=5

In [42]:
np11

array([ 7,  9, 11, 13], dtype=int16)

In [43]:
np11 > 10

array([False, False,  True,  True])

In [44]:
np11 ==11

array([False, False,  True, False])

In [46]:
np11.__le__(9)

array([ True,  True, False, False])

In [47]:
np11

array([ 7,  9, 11, 13], dtype=int16)

In [48]:
np12 

array([ 3,  6,  9, 12, 15], dtype=int16)

In [49]:
np11.size

4

In [50]:
np11.nbytes

8

In [51]:
np11.itemsize

2

In [53]:
np13 = np.arange(1,11)

In [54]:
np13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
np13[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
np13[3:7]

array([4, 5, 6, 7])

In [58]:
np13[3:7] +5 # 이거는 np13에 저장되지 않고 나타내기만 한다.

array([ 9, 10, 11, 12])

In [59]:
np13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
np13 = np13[3:7] + 5

In [61]:
np13 # 4부터 7까지 5를 np13에 더하고 

array([ 9, 10, 11, 12])

In [62]:
np14 = np.arange(1,11)

In [63]:
np14[2:5] +=3

In [64]:
np14

array([ 1,  2,  6,  7,  8,  6,  7,  8,  9, 10])

In [65]:
np15 = np14

In [66]:
np14[4] =90

In [67]:
np15

array([ 1,  2,  6,  7, 90,  6,  7,  8,  9, 10])

In [68]:
np16 = np14.copy() #np16에 np14를 copy()를 복사해서 넣어주면 np14내에 수를 바꿔도 np16이 변하지 않는다.

In [69]:
np14
np16

array([ 1,  2,  6,  7, 90,  6,  7,  8,  9, 10])

In [70]:
np16

array([ 1,  2,  6,  7, 90,  6,  7,  8,  9, 10])

In [71]:
np14[2] = 123

In [72]:
np14

array([  1,   2, 123,   7,  90,   6,   7,   8,   9,  10])

In [73]:
np16

array([ 1,  2,  6,  7, 90,  6,  7,  8,  9, 10])

In [75]:
np14[7:] = 0

np14 에서 0에서 6번째 까지 다 0으로 바꾼다.

In [76]:
np14

array([  1,   2, 123,   7,  90,   6,   7,   0,   0,   0])

In [77]:
np22 = np.array([[1,2,3],[3,4,5]])

In [78]:
a1 =[1,2,31]
a2 = [2,4,6]
np20 = np.array([a1, a2])

In [79]:
np20

array([[ 1,  2, 31],
       [ 2,  4,  6]])

In [80]:
np2 = np.arange(1,16)

In [81]:
np2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [82]:
np222 = np2.reshape(3,5)

In [83]:
np14

array([  1,   2, 123,   7,  90,   6,   7,   0,   0,   0])

In [85]:
np144 = np14.reshape(2,5)

In [86]:
np144

array([[  1,   2, 123,   7,  90],
       [  6,   7,   0,   0,   0]])

In [87]:
np222 = np2.reshape(3,5)

In [88]:
np2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [89]:
np2[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [90]:
np222[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [91]:
np222[1:2]

array([[ 6,  7,  8,  9, 10]])

In [92]:
np222

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [93]:
np222[1][3]

9

In [94]:
np22

array([[1, 2, 3],
       [3, 4, 5]])

In [95]:
b = a.array()

AttributeError: ignored

In [96]:
a

[[2, 3, 4, 5, 6, 7, 8, 9],
 [4, 6, 8, 10, 12, 14, 16, 18],
 [6, 9, 12, 15, 18, 21, 24, 27],
 [8, 12, 16, 20, 24, 28, 32, 36],
 [10, 15, 20, 25, 30, 35, 40, 45],
 [12, 18, 24, 30, 36, 42, 48, 54],
 [14, 21, 28, 35, 42, 49, 56, 63],
 [16, 24, 32, 40, 48, 56, 64, 72],
 [18, 27, 36, 45, 54, 63, 72, 81]]

In [97]:
a[:]

[[2, 3, 4, 5, 6, 7, 8, 9],
 [4, 6, 8, 10, 12, 14, 16, 18],
 [6, 9, 12, 15, 18, 21, 24, 27],
 [8, 12, 16, 20, 24, 28, 32, 36],
 [10, 15, 20, 25, 30, 35, 40, 45],
 [12, 18, 24, 30, 36, 42, 48, 54],
 [14, 21, 28, 35, 42, 49, 56, 63],
 [16, 24, 32, 40, 48, 56, 64, 72],
 [18, 27, 36, 45, 54, 63, 72, 81]]

In [98]:
a[:2]

[[2, 3, 4, 5, 6, 7, 8, 9], [4, 6, 8, 10, 12, 14, 16, 18]]

In [99]:
a[1:3]

[[4, 6, 8, 10, 12, 14, 16, 18], [6, 9, 12, 15, 18, 21, 24, 27]]

In [101]:
a[ : , : ]

TypeError: ignored

In [102]:
a.np

AttributeError: ignored

In [104]:
b = np.array(a) #list를 numpy에서는 np.array를 사용해야 한다.

In [105]:
b

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 4,  6,  8, 10, 12, 14, 16, 18],
       [ 6,  9, 12, 15, 18, 21, 24, 27],
       [ 8, 12, 16, 20, 24, 28, 32, 36],
       [10, 15, 20, 25, 30, 35, 40, 45],
       [12, 18, 24, 30, 36, 42, 48, 54],
       [14, 21, 28, 35, 42, 49, 56, 63],
       [16, 24, 32, 40, 48, 56, 64, 72],
       [18, 27, 36, 45, 54, 63, 72, 81]])

In [106]:
b[:,:]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 4,  6,  8, 10, 12, 14, 16, 18],
       [ 6,  9, 12, 15, 18, 21, 24, 27],
       [ 8, 12, 16, 20, 24, 28, 32, 36],
       [10, 15, 20, 25, 30, 35, 40, 45],
       [12, 18, 24, 30, 36, 42, 48, 54],
       [14, 21, 28, 35, 42, 49, 56, 63],
       [16, 24, 32, 40, 48, 56, 64, 72],
       [18, 27, 36, 45, 54, 63, 72, 81]])

In [107]:
b[2:3, :]

array([[ 6,  9, 12, 15, 18, 21, 24, 27]])

In [108]:
b[2:3, :] +50

array([[56, 59, 62, 65, 68, 71, 74, 77]])

In [109]:
c = np.array(b, dtype=np.int16)

In [110]:
c

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 4,  6,  8, 10, 12, 14, 16, 18],
       [ 6,  9, 12, 15, 18, 21, 24, 27],
       [ 8, 12, 16, 20, 24, 28, 32, 36],
       [10, 15, 20, 25, 30, 35, 40, 45],
       [12, 18, 24, 30, 36, 42, 48, 54],
       [14, 21, 28, 35, 42, 49, 56, 63],
       [16, 24, 32, 40, 48, 56, 64, 72],
       [18, 27, 36, 45, 54, 63, 72, 81]], dtype=int16)

In [111]:
c.dtype

dtype('int16')

In [112]:
b[1, 0:2]

array([4, 6])

b의 배열에 1행에서 1열까지 나타낸다.

In [113]:
b[-1, 0:2]

array([18, 27])

In [115]:
np3 = np.arange(1,25)

In [118]:
np3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

np3를 1 부터 24까지 만든다.

In [117]:
np33 = np.random.randn(24)

In [119]:
np33

array([ 1.0583677 ,  0.41921798, -2.7800285 , -0.06712881,  1.3687004 ,
       -0.9679867 ,  0.64345583, -0.17160591, -1.44240022,  1.83531887,
       -0.58007129, -0.9349472 , -0.48843843,  1.01183324, -0.11048545,
       -1.08242611,  2.24828852,  0.86589816,  1.53799188,  1.91826051,
        0.55795884,  0.15565361, -0.58595451,  1.46058804])

np33를 24개의 랜덤 숫자를 만든다.

In [120]:
np33.shape

(24,)

np33 의 형태 즉 갯수를 나타낸다.

In [121]:
np33.reshape(2,3,4)

array([[[ 1.0583677 ,  0.41921798, -2.7800285 , -0.06712881],
        [ 1.3687004 , -0.9679867 ,  0.64345583, -0.17160591],
        [-1.44240022,  1.83531887, -0.58007129, -0.9349472 ]],

       [[-0.48843843,  1.01183324, -0.11048545, -1.08242611],
        [ 2.24828852,  0.86589816,  1.53799188,  1.91826051],
        [ 0.55795884,  0.15565361, -0.58595451,  1.46058804]]])

np33을 2개의 행렬로 나누고 각 행렬은 3행 4열이 된다.

In [122]:
np33 * 100

array([ 105.83676988,   41.92179846, -278.0028499 ,   -6.71288066,
        136.87004024,  -96.79867039,   64.3455834 ,  -17.16059107,
       -144.24002167,  183.53188709,  -58.00712932,  -93.49472009,
        -48.84384308,  101.1833237 ,  -11.04854458, -108.24261108,
        224.82885176,   86.5898165 ,  153.79918823,  191.82605141,
         55.7958843 ,   15.56536114,  -58.59545055,  146.05880372])

In [123]:
np333 = np33.reshape(2,3,4)

In [124]:
np333

array([[[ 1.0583677 ,  0.41921798, -2.7800285 , -0.06712881],
        [ 1.3687004 , -0.9679867 ,  0.64345583, -0.17160591],
        [-1.44240022,  1.83531887, -0.58007129, -0.9349472 ]],

       [[-0.48843843,  1.01183324, -0.11048545, -1.08242611],
        [ 2.24828852,  0.86589816,  1.53799188,  1.91826051],
        [ 0.55795884,  0.15565361, -0.58595451,  1.46058804]]])

In [125]:
np3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [126]:
np3.reshape(2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [127]:
np3 = np.arange(10, 241, 10)

In [128]:
np3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240])

In [129]:
np3.ndim

1

np3.ndim 에서 ndim은 몇 차원인지 나타내는 것이다.
여기서는 np3는 1차원이다.

In [130]:
np3 = np.arange(10,241,10)

In [131]:
np3.ndim

1

In [132]:
np3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240])

In [133]:
np33

array([ 1.0583677 ,  0.41921798, -2.7800285 , -0.06712881,  1.3687004 ,
       -0.9679867 ,  0.64345583, -0.17160591, -1.44240022,  1.83531887,
       -0.58007129, -0.9349472 , -0.48843843,  1.01183324, -0.11048545,
       -1.08242611,  2.24828852,  0.86589816,  1.53799188,  1.91826051,
        0.55795884,  0.15565361, -0.58595451,  1.46058804])

In [134]:
np333 = np3. reshape(2,12)

np3를 np333으로 바꾸고 2행 12열로 만든다.

In [136]:
np333

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]])

In [137]:
np3333 = np333.reshape(2,3,4)

np3333을 3차원으로 만드는 데 2개의 행렬로 나누고 각 행은 3행 4열로 만든다.

In [138]:
np444 = np333.reshape(2,3,2,2)

In [139]:
np444.ndim

4

In [142]:
np444

array([[[[ 10,  20],
         [ 30,  40]],

        [[ 50,  60],
         [ 70,  80]],

        [[ 90, 100],
         [110, 120]]],


       [[[130, 140],
         [150, 160]],

        [[170, 180],
         [190, 200]],

        [[210, 220],
         [230, 240]]]])

In [143]:
  np333

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]])

In [144]:
np3333

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])

In [145]:
np3333[2:]

array([], shape=(0, 3, 4), dtype=int64)

In [146]:
np3333[:,:,:]

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])

In [147]:
np3333[:,0:0,2:3]

array([], shape=(2, 0, 1), dtype=int64)

In [155]:
np3333[0:1,0:1,2:3]

array([[[30]]])

In [157]:
np3333[0:1,2:3,:]

array([[[ 90, 100, 110, 120]]])

In [158]:
np3333[1:2,1:3,0:2]

array([[[170, 180],
        [210, 220]]])

In [178]:
np123 = np3333

In [179]:
np123

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])

In [190]:
np123[0:2,1:3,2:4] , np123[1:3, 1:3,2:4]

(array([[[ 70,  80],
         [110, 120]],
 
        [[190, 200],
         [230, 240]]]), array([[[190, 200],
         [230, 240]]]))

In [195]:
np123[0:2,1:3,2:4]

array([[[ 70,  80],
        [110, 120]],

       [[190, 200],
        [230, 240]]])

In [204]:
np123[0:1,1:3,2:4] np123[1:3,0:2,2:4]

array([[[220, 240],
        [300, 320]]])

In [206]:
np123[:,1:,2:]

array([[[ 70,  80],
        [110, 120]],

       [[190, 200],
        [230, 240]]])